# Generated by Django 2.1 on 2019-07-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190703_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='launguage',
            new_name='language',
        ),
    ]
